packages:
  - apps/*
  - packages/*

allowBuilds:
  '@apollo/protobufjs': true
  '@clerk/shared': true
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  '@swc/core': true
  '@tailwindcss/oxide': true
  better-sqlite3: true
  core-js-pure: true
  esbuild: true
  lefthook: true
  napi-postinstall: true
  oxc-resolver: true
  prisma: true
  sharp: true
