packages:
  - apps/*
  - packages/*

allowBuilds:
  '@apollo/protobufjs': true
  '@clerk/shared': true
  '@prisma/client': true
  '@prisma/engines': true
  '@tailwindcss/oxide': true
  better-sqlite3: true
  esbuild: true
  lefthook: true
  oxc-resolver: true
  prisma: true
  sharp: true

minimumReleaseAgeExclude:
  - '@ai-sdk/gateway@4.0.4'
  - '@ai-sdk/groq@4.0.1'
  - '@ai-sdk/mcp@2.0.3'
  - '@ai-sdk/provider-utils@5.0.1'
  - '@ai-sdk/react@4.0.5'
  - ai@7.0.4
