packages:
  - apps/*
  - '!apps/hackernews'
  - packages/*

onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - esbuild
  - prisma
  - sharp
