packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@clerk/shared'
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - prisma
  - sharp
