export default (props: React.PropsWithChildren) => {
    return (
        <html lang = 'en'>
            <body>{props.children}</body>
        </html>
    );
};

export const metadata = {
    title:       'Next.js',
    description: 'Generated by Next.js',
};
